Repository ShellTux/VitalVue, pull requests merged in 2024-05, with the labels that each got.

#19 6 user authentication
  src/IndividualTypes/IndividualTypes.py
  src/app.py
Labels: enhancement

#23 10 get prescriptions
  assets/onda.json
  db-config/setup.sql
  src/app.py
Labels: enhancement

#22 8 see appointments
  src/app.py
Labels: enhancement

#21 9 schedule surgery
  db-config/setup.sql
  src/app.py
Labels: enhancement

#20 7 schedule appointment
  db-config/setup.sql
  src/app.py
Labels: enhancement

#28 7 schedule appointment
  src/app.py
Labels: enhancement

#31 add trigger from surgery schedule
  db-config/02-functions.sql
  db-config/03-triggers.sql
Labels: enhancement

#30 9 schedule surgery
  db-config/01-setup.sql
  src/app.py
Labels: enhancement

#32 update database tables and trigger functions
  assets/onda.json
  db-config/01-setup.sql
  db-config/02-functions.sql
Labels: enhancement

#33 update endpoint to receive appointment cost
  src/app.py
Labels: enhancement

#24 15 Generate a monthly report
  postman/endpoints.sh
  src/app.py
Labels: enhancement, help wanted, testing needed

#26 14 daily summary
  postman/endpoints.sh
  src/app.py
Labels: enhancement

#35 fix problem with statement formatting
  src/app.py
Labels: enhancement

#36 9 schedule surgery
  db-config/01-setup.sql
  db-config/02-functions.sql
  src/app.py
Labels: enhancement

#34 update appointment trigger function
  db-config/01-setup.sql
  db-config/02-functions.sql
  src/app.py
Labels: enhancement

#37 improve statement building code
  src/app.py
Labels: enhancement

#38 11 add prescriptions
  db-config/01-setup.sql
  db-config/02-functions.sql
  db-config/03-triggers.sql
  src/app.py
Labels: enhancement

#39 10 get prescriptions
  src/app.py
Labels: enhancement

#40 add function and trigger to associate prescription with patient
  db-config/02-functions.sql
  db-config/03-triggers.sql
Labels: enhancement

#41 10 get prescriptions
  src/app.py
Labels: enhancement

#43 10 get prescriptions
  db-config/02-functions.sql
  src/app.py
Labels: enhancement

#44 Documentation
  src/app.py
Labels: documentation

#45 Manuals
  Makefile
  docs/examples/installation-manual.md
  docs/examples/presentation.md
  docs/examples/user-manual.md
  docs/installation-manual.md
  docs/presentation.md
  docs/relatorio.md
  docs/user-manual.md
  example.env
  pandoc/filters/image-path.lua
  postman/VitalVue.postman_collection.json
  requirements.txt
Labels: documentation

#47 Development
  Makefile
  assets/er-diagram.png
  assets/onda.json
  assets/physical-diagram.png
  db-config/01-setup.sql
  db-config/03-triggers.sql
  docs/installation-manual.md
  docs/presentation.md
  docs/relatorio.md
  docs/user-manual.md
  postman/1. Vital Vue Register.postman_collection.json
  postman/2. Vital Vue Appointments.postman_collection.json
  postman/3. Vital Vue Surgeries.postman_collection.json
  postman/4. Vital Vue Prescriptions.postman_collection.json
  postman/5. Vital Vue Stats.postman_collection.json
  postman/VitalVue.postman_collection.json
  src/app.py
Labels: documentation, enhancement

#48 Develop
  .gitignore
  Makefile
  README.md
  assets/er-diagram.png
  assets/onda.json
  assets/physical-diagram.png
  config/example.sql
  config/setup.sql
  db-config/01-setup.sql
  db-config/02-functions.sql
  db-config/03-triggers.sql
  docker-compose.yml
  docs/examples/installation-manual.md
  docs/examples/presentation.md
  docs/examples/user-manual.md
  docs/presentation.md
  docs/relatorio.md
  example.env
  examples/example.sql
  logging_config.ini
  pandoc/filters/image-path.lua
  postman/1. Vital Vue Register.postman_collection.json
  postman/2. Vital Vue Appointments.postman_collection.json
  postman/3. Vital Vue Surgeries.postman_collection.json
  postman/4. Vital Vue Prescriptions.postman_collection.json
  postman/5. Vital Vue Stats.postman_collection.json
  postman/endpoints.sh
  requirements.txt
  src/IndividualTypes/IndividualTypes.py
  src/IndividualTypes/__init__.py
  src/StatusCode/StatusCode.py
  src/StatusCode/__init__.py
  src/app.py
Labels: documentation, enhancement
